apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
data:
  # Base64 encoded "postgres" password
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=
